---
fail_fast: false
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
  - repo: https://github.com/BlankSpruce/gersemi
    rev: 0.26.0
    hooks:
      - id: gersemi
